<?php
use PrestaShop\PrestaShop\Core\Payment\PaymentOption;

class fena extends PaymentModule
{
    public function __construct()
    {
        $this->name = "Fena";
        $this->author = "Qasim_Malik";
        $this->version = '1.0.0';
        $this->bootstrap = true;

        
        $this->tab = 'payments_gateways';
        $this->displayName = $this->l('Fena');
        $this->description = $this->l("The fastest way to pay via Open Banking");
        $this->ps_versions_compliancy = array('min' => '1.7.0.0', 'max' => '1.7.8.99');
        parent::__construct();
    }
    public function install()
    {
        return parent::install()
        && $this->registerHook('Header')
            && $this->registerHook('displayPaymentReturn')
            && $this->registerHook('paymentOptions');
    }
    public function uninstall()
    {
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }
    public function hookDisplayPaymentReturn(){
        $this->context->smarty->assign(array());
        return $this->display(__FILE__,'views/templates/hook/return.tpl');
    }
    public function hookPaymentOptions(){
        $fena = new PaymentOption();
        $fena->setModuleName($this->name)
            ->setCallToActionText('Pay by Fena')
            ->setAdditionalInformation('Pay faster via Fena Open Banking')
            ->setAction($this->context->link->getModuleLink($this->name,'payment'));
        return[$fena];
    }
    public function hookHeader(){
        $this->context->controller->addCSS(array(
            $this->_path.'views/css/fena.css'
        ));
        $this->context->controller->addJS(array(
            $this->_path.'views/js/fena.js'
        ));
    }
    public function getContent(){

        if (Tools::isSubmit('fenaClient')){
            $clientId= Tools::getValue('clientId');
            $clientSecret=Tools::getValue('clientSecret');
            Configuration::updateValue('FENA_CLIENTID',$clientId);
            Configuration::updateValue('FENA_CLIENTSECRET',$clientSecret);
        }
        $this->context->smarty->assign(array(
          'FENA_CLIENTID'=>Configuration::get('FENA_CLIENTID')
        ));
        $this->context->smarty->assign(array(
           'FENA_CLIENTSECRET'=>Configuration::get('FENA_CLIENTSECRET')
        ));

    return $this->display(__FILE__,'views/templates/admin/configuration.tpl');
}
    }